import {
  BarChart3,
  FileText,
  Layers,
  LayoutDashboard,
  MessageCircle,
  QrCode,
  Receipt,
  Send,
  Settings,
  ShieldCheck,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";
export const nav = [
  ["Dashboard", LayoutDashboard],
  ["Customers", Users],
  ["Schemes", Layers],
  ["Payments", Wallet],
  ["Payment proofs", Receipt],
  ["Gold rates", TrendingUp],
  ["WhatsApp", QrCode],
  ["WhatsApp inbox", MessageCircle],
  ["Messages", Send],
  ["Reports", BarChart3],
  ["Settings", Settings],
  ["Staff", ShieldCheck],
  ["Audit log", FileText],
] as const;
